project_id = "kcnrnietrmaldtlltfpp"

[functions.playlist-automation]
verify_jwt = true

[functions.stream-playlist]
verify_jwt = false

[functions.validate-activation-key]
verify_jwt = false

[functions.generate-activation-key]
verify_jwt = false
