project_id = "kcnrnietrmaldtlltfpp"

[functions.stream-playlist]
verify_jwt = false

[functions.validate-activation-key]
verify_jwt = false

[functions.generate-activation-key]
verify_jwt = false

[functions.ffmpeg-cloud]
verify_jwt = true

[functions.ffmpeg-webhook]
verify_jwt = false
